/**
 * GÉNÉRÉ par `node packages/bareme-sacem/gen-fiches.mjs`. Ne pas éditer.
 *
 * La carte des fiches du barème, en imports explicites. Voir le script pour
 * la raison : un import à trou cesse d'être analysé une fois le paquet
 * installé en dépendance, et les fiches disparaissent du build en silence.
 */
export const FICHES: Record<string, () => Promise<unknown>> = {
  "agence-bureau-ouvert-public": () => import("./fiches/agence-bureau-ouvert-public.json"),
  "animation-chr": () => import("./fiches/animation-chr.json"),
  "attente-telephonique": () => import("./fiches/attente-telephonique.json"),
  "audiovisuel-musique-accompagnement": () => import("./fiches/audiovisuel-musique-accompagnement.json"),
  "bar-karaoke-piste-danse": () => import("./fiches/bar-karaoke-piste-danse.json"),
  "bowling-salle-jeux": () => import("./fiches/bowling-salle-jeux.json"),
  "cafe-restaurant-traditionnel": () => import("./fiches/cafe-restaurant-traditionnel.json"),
  "camping": () => import("./fiches/camping.json"),
  "centre-soins-detente": () => import("./fiches/centre-soins-detente.json"),
  "ceremonie-obseques": () => import("./fiches/ceremonie-obseques.json"),
  "cinema": () => import("./fiches/cinema.json"),
  "club-sport-amateur": () => import("./fiches/club-sport-amateur.json"),
  "club-sport-professionnel": () => import("./fiches/club-sport-professionnel.json"),
  "commune-moins-5000-habitants": () => import("./fiches/commune-moins-5000-habitants.json"),
  "concert-spectacle-seance-dansante": () => import("./fiches/concert-spectacle-seance-dansante.json"),
  "cours-danse-gymnastique": () => import("./fiches/cours-danse-gymnastique.json"),
  "ecoute-visualisation-en-ligne-unite": () => import("./fiches/ecoute-visualisation-en-ligne-unite.json"),
  "enseignement-superieur": () => import("./fiches/enseignement-superieur.json"),
  "etablissement-culturel": () => import("./fiches/etablissement-culturel.json"),
  "etablissement-sante": () => import("./fiches/etablissement-sante.json"),
  "festival": () => import("./fiches/festival.json"),
  "hebergement-touristique": () => import("./fiches/hebergement-touristique.json"),
  "institution-sociale-medicosociale": () => import("./fiches/institution-sociale-medicosociale.json"),
  "karting": () => import("./fiches/karting.json"),
  "local-associatif": () => import("./fiches/local-associatif.json"),
  "magasin-commerce-detail": () => import("./fiches/magasin-commerce-detail.json"),
  "manifestation-musique-fond-sonore": () => import("./fiches/manifestation-musique-fond-sonore.json"),
  "manifestation-sportive-occasionnelle": () => import("./fiches/manifestation-sportive-occasionnelle.json"),
  "meuble-tourisme-chambre-hote": () => import("./fiches/meuble-tourisme-chambre-hote.json"),
  "musique-college-lycee": () => import("./fiches/musique-college-lycee.json"),
  "musique-ecole-creche-loisirs": () => import("./fiches/musique-ecole-creche-loisirs.json"),
  "musique-entreprise-administration": () => import("./fiches/musique-entreprise-administration.json"),
  "parc-attractions-loisirs": () => import("./fiches/parc-attractions-loisirs.json"),
  "parc-stationnement": () => import("./fiches/parc-stationnement.json"),
  "patinoire": () => import("./fiches/patinoire.json"),
  "piscine-plage": () => import("./fiches/piscine-plage.json"),
  "restauration-rapide": () => import("./fiches/restauration-rapide.json"),
  "retransmission-sportive": () => import("./fiches/retransmission-sportive.json"),
  "reveillon": () => import("./fiches/reveillon.json"),
  "salle-attente": () => import("./fiches/salle-attente.json"),
  "salle-concert-theatre": () => import("./fiches/salle-concert-theatre.json"),
  "salle-sport-fitness": () => import("./fiches/salle-sport-fitness.json"),
  "salon-coiffure": () => import("./fiches/salon-coiffure.json"),
  "site-internet-marchand": () => import("./fiches/site-internet-marchand.json"),
  "site-internet-monetise": () => import("./fiches/site-internet-monetise.json"),
  "spectacle-pluralite-genre": () => import("./fiches/spectacle-pluralite-genre.json"),
  "station-service": () => import("./fiches/station-service.json"),
  "telechargement-a-la-demande": () => import("./fiches/telechargement-a-la-demande.json"),
  "transport-routier-voyageur": () => import("./fiches/transport-routier-voyageur.json"),
};
